// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resc.Src;

namespace Resc.Migrations
{
    [DbContext(typeof(RescContext))]
    [Migration("20181117002326_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Resc.Src.RescContext+ActivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FirstResponderId");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.HasKey("Id");

                    b.HasIndex("FirstResponderId");

                    b.ToTable("ActivePositions");
                });

            modelBuilder.Entity("Resc.Src.RescContext+FirstResponder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("PushAuth");

                    b.Property<string>("PushEndpoint");

                    b.Property<string>("PushKey");

                    b.HasKey("Id");

                    b.ToTable("FirstResponders");
                });

            modelBuilder.Entity("Resc.Src.RescContext+FirstResponderIntervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FirstResponderId");

                    b.Property<int>("InterventionId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("FirstResponderId");

                    b.HasIndex("InterventionId");

                    b.ToTable("FirstResponderInterventions");
                });

            modelBuilder.Entity("Resc.Src.RescContext+Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detail");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("Overview");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("Resc.Src.RescContext+Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Resc.Src.RescContext+ActivePosition", b =>
                {
                    b.HasOne("Resc.Src.RescContext+FirstResponder", "FirstResponder")
                        .WithMany()
                        .HasForeignKey("FirstResponderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Resc.Src.RescContext+FirstResponderIntervention", b =>
                {
                    b.HasOne("Resc.Src.RescContext+FirstResponder", "FirstResponder")
                        .WithMany()
                        .HasForeignKey("FirstResponderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Resc.Src.RescContext+Intervention", "Intervention")
                        .WithMany()
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
