// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resc.Src;

namespace Resc.Migrations
{
    [DbContext(typeof(RescContext))]
    partial class RescContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Resc.Src.RescContext+ActivePosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FirstResponderId");

                    b.Property<decimal>("Lat");

                    b.Property<decimal>("Lng");

                    b.HasKey("Id");

                    b.HasIndex("FirstResponderId");

                    b.ToTable("ActivePositions");
                });

            modelBuilder.Entity("Resc.Src.RescContext+FirstResponder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("FirstResponder");
                });

            modelBuilder.Entity("Resc.Src.RescContext+ActivePosition", b =>
                {
                    b.HasOne("Resc.Src.RescContext+FirstResponder", "FirstResponder")
                        .WithMany()
                        .HasForeignKey("FirstResponderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
